module.exports = {
    EVENT_PLAYLIST_END: 'EVENT_PLAYLIST_END',
    EVENT_NEW_SONG: 'EVENT_NEW_SONG',
    EVENT_PLAYLIST_DURATION_EXPIRED: 'EVENT_PLAYLIST_DURATION_EXPIRED',
    EVENT_PLAYLIST_DURATION_EXPIRED_SONG: 'EVENT_PLAYLIST_DURATION_EXPIRED_SONG',
};
